apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quantcompass-backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/awesome-sphere-449619-e4/quantcompass-backend
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: FLASK_ENV
          value: "production"
        - name: POLYGON_API_KEY
          valueFrom:
            secretKeyRef:
              name: polygon-api-key
              key: key
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: email-config
              key: user
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: email-config
              key: password
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-config
              key: bot_token
        - name: TELEGRAM_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: telegram-config
              key: channel_id
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
